name: flutter_express
description: Flutter_Express is a lightweight and user-friendly routing package. It's perfect for swiftly crafting web applications, prototypes, or smaller projects without drowning in unnecessary complexity.
version: 0.6.0
repository: https://github.com/athulacaj/flutter_express
environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  http: ^1.1.0

