name: dart_express
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  mime: ^1.0.4
  path: ^1.8.0
  http_parser: ^4.0.2
  shelf: ^1.4.1
  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  http: ^1.1.0

