name: flutter_express
description: A routing package for dart.
version: 0.6.0
repository: https://github.com/athulacaj/dart_express

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  http: ^1.1.0

